status_led:
  pin: 23

web_server:
  port: 80

uart:
  id: range_uart
  tx_pin: GPIO32
  rx_pin: GPIO33
  baud_rate: 9600

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a  

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address ${short_name}
    ssid:
      name: ESP Connected SSID ${short_name}
    bssid:
      name: ESP Connected BSSID ${short_name}
    mac_address:
      name: ESP Mac Wifi Address ${short_name}
    # scan_results:
      # name: ESP Latest Scan Results ${short_name}
      
sensor:
  - platform: wifi_signal
    name: WiFi Signal ${short_name} 

  - platform: uptime
    name: Uptime ${short_name}   

  - platform: "jsn_sr04t"
    name: "Distance"
    update_interval: 1s
    uart_id: range_uart
  
binary_sensor:
  - platform: gpio
    pin:
      number: 34
#      inverted: True
    name: "${friendly_name_wicket} ${short_name}"
    internal: true

  - platform: gpio
    pin:
      number: 35
#      inverted: True
    name: "${friendly_name_gate} ${short_name}"
    internal: true
# =======
    device_class: door
    icon: mdi:door-open
    pin:
      number: 34
      inverted: True
    name: "${friendly_name_wicket} ${short_name}"
#    internal: true

  - platform: gpio
    device_class: garage_door
    icon: mdi:gate-open
    pin:
      number: 35
      inverted: True
    name: "${friendly_name_gate} ${short_name}"
#    internal: true
    

#  Pin  	  Pin Label  	  GPIO  	  Safe to use?  	Reason
#4	SENSOR_VP	GPIO36		Input only GPIO, cannot be configured as output
#5	SENSOR_VN	GPIO39		Input only GPIO, cannot be configured as output
#6	IO34	GPIO34		Input only GPIO, cannot be configured as output   Геркон ворота
#7	IO35	GPIO35		Input only GPIO, cannot be configured as output   Геркон Калитка
#8	IO32	GPIO32		TX Soft
#9	IO33	GPIO33		RX Soft
#10	IO25	GPIO25		
#11	IO26	GPIO26		
#12	IO27	GPIO27		Дальномер
#13	IO14	GPIO14		
#14	IO12	GPIO12		must be LOW during boot
#16	IO13	GPIO13		
#17	SHD/SD2	GPIO9		Connected to Flash memory
#18	SWP/SD3	GPIO10		Connected to Flash memory
#19	SCS/CMD	GPIO11		Connected to Flash memory
#20	SCK/CLK	GPIO6		Connected to Flash memory
#21	SDO/SD0	GPIO7		Connected to Flash memory
#22	SDI/SD1	GPIO8		Connected to Flash memory
#23	IO15	GPIO15		must be HIGH during boot, prevents startup log if pulled LOW
#24	IO2	GPIO2		must be LOW during boot and also connected to the on-board LED
#25	IO0	GPIO0		must be HIGH during boot and LOW for programming
#26	IO4	GPIO4		
#27	IO16	GPIO16		Relay-1
#28	IO17	GPIO17		Relay-2
#29	IO5	GPIO5		must be HIGH during boot
#30	IO18	GPIO18		
#31	IO19	GPIO19		
#33	IO21	GPIO21		SDA (I2C)
#34	RXD0	GPIO3		Rx pin, used for flashing and debugging
#35	TXD0	GPIO1		Tx pin, used for flashing and debugging
#36	IO22	GPIO22		SCL (I2C)
#37	IO23	GPIO23	LED	
