status_led:
  pin: 23

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address ${short_name}
    ssid:
      name: ESP Connected SSID ${short_name}
    bssid:
      name: ESP Connected BSSID ${short_name}
    mac_address:
      name: ESP Mac Wifi Address ${short_name}
    # scan_results:
      # name: ESP Latest Scan Results ${short_name}
      
sensor:
  - platform: wifi_signal
    name: WiFi Signal ${short_name} 
  - platform: uptime
    name: Uptime ${short_name}   
  
  