status_led:
  pin: 23
  
web_server:
  port: 80

switch:
   - platform: gpio
     pin: 16
     id: relay1
     restore_mode: ${relay1_restore_mode}
     name: "${friendly_name_gate} Remote"
     icon: "mdi:gate"
     on_turn_on:
     - delay: 500ms
     - switch.turn_off: relay1

   - platform: gpio
     pin: 17
     id: relay2
     restore_mode: ${relay2_restore_mode}
     name: "${friendly_name_wicket} Remote"
     icon: "mdi:gate"
     on_turn_on:
     - delay: 500ms
     - switch.turn_off: relay2


button:
   - platform: restart
     name: Restart ${short_name}  
  
>>>>>>> 21f582aadbc346a9dd8cc68327b2222fc373cc17
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address ${short_name}
    ssid:
      name: ESP Connected SSID ${short_name}
    bssid:
      name: ESP Connected BSSID ${short_name}
    mac_address:
      name: ESP Mac Wifi Address ${short_name}
    # scan_results:
      # name: ESP Latest Scan Results ${short_name}
      
sensor:
  - platform: wifi_signal
    name: WiFi Signal ${short_name} 
  - platform: uptime
    name: Uptime ${short_name}   
  
  