esphome:
  name: "${name}"
  name_add_mac_suffix: true
#  includes:
#    - my_matrixled_display.h
  platformio_options:
    upload_speed: 115200

  on_boot:
    then:
      - light.turn_on:
          id: my_light
          brightness: 80%
          color_brightness: 100%
          red: 100%
          green: 0%
          blue: 100%  
      # - lambda: |-
           # id(my_temp_corect_float) = id(temp_correct).state;
           # ESP_LOGI("main", "Value of my number 0: %f", id(my_temp_corect_float));
          
          
esp32:    
 
  board: esp32dev
#  restore_from_flash: true
  framework:
    type: arduino
#    version: 2.0.6




# Enable logging
logger:
  level: VERBOSE
# VERY_VERBOSE
#---------------------------------------------------------------------------------#  

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password_old

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${true_address}
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "TS-Atom-M5 Fallback Hotspot"
    password: "12345678"

captive_portal:


# mqtt:
 # broker: !secret mqtt_broker
 # username: MqTTUzver
 # password: !secret mqtt_password
 # discovery_unique_id_generator: mac
 # discovery: true
 
 
# text_sensor:
  # - platform: mqtt_subscribe
    # name: "Text"
    # id: extratext
    # topic: ${name}/sensor/cantemprache/state

web_server:
  port: 80

