sensor:
  - platform: wifi_signal
    name: WiFi Signal ${short_name} 
  - platform: uptime
    name: Uptime ${short_name} 
    
  - platform: qmp6988
    temperature:
      name: "Temperatur6988e ${short_name}"
      oversampling: 16x
    pressure:
      name: "Pressure ${short_name}"
      oversampling: 16x
    address: 0x70
    update_interval: 60s
    iir_filter: 2x
  - platform: sht3xd
#    optimistic: true
    temperature:
      force_update: true
      name: "Temperature ${short_name}"
      id: temp_sht3xd
      filters:
        - lambda: return x + id(temp_correct).state ;
    humidity:
      name: "Humidity ${short_name}"
      id: hum_sht3xd
      force_update: true
    address: 0x44
    update_interval: 60s