sensor:
  - platform: wifi_signal
    name: WiFi Signal ${short_name} 
  - platform: uptime
    name: Uptime ${short_name} 

  - platform: dallas_temp
    address: 0xc600000ca617a628
    name: "Temperature ${short_name}"
    id: tepm_pool
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
