sensor:
  - platform: wifi_signal
    name: WiFi Signal ${short_name} 
  - platform: uptime
    name: Uptime ${short_name} 
#  - platform: internal_temperature
#    name: "Internal Temperature"

  - platform: dallas
#    address: 0xc600000ca617a628
    index: 0
    name: "Temperature ${short_name}"
    id: tepm_pool
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
    on_value_range:
      - above: !lambda 'return id(set_temp_pool).state;'
        then:
          - switch.turn_off: relay2
      - below: !lambda 'return id(set_temp_pool).state;'
        then:
          if:
            condition:
              - switch.is_on: relay1
            then: 
              - switch.turn_on: relay2
      # - above: 5.0
        # below: 10.0
        # then:
          # - switch.turn_on: relay_2
